Sdks 3608 add missing docs
ForgeRock/ping-ios-sdk pull request #18
Opened 2024-12-09 21:51 UTC by vahancouver

[SDKS-3608](https://pingidentity.atlassian.net/browse/SDKS-3608) [iOS][Ping SDK] Missing docs for public interfaces

Also updated the podspecs and file copyrights

2024-12-09 22:21 UTC, spetrov requested changes
I found only one typo to be fixed... everything else looks very good! 👍🏻

2024-12-10 00:32 UTC, vahancouver commented on Oidc/Oidc/OpenIdConfiguration.swift
> +/// Struct epresenting the OpenID Connect configuration.
fixed

2024-12-10 00:34 UTC, vahancouver commented on Storage/Storage/Encryptor.swift
> +  /// Decrypts the given data.
@spetrov in protocol definitions we cannot specify access modifiers 
(XCODE: Protocol requirements implicitly have the same access as the protocol itself)

2024-12-10 00:34 UTC, vahancouver commented on Storage/Storage/Encryptor.swift
>    func encrypt(data: Data) async throws -> Data
Same here

2024-12-10 01:02 UTC, spetrov approved these changes

2024-12-10 15:39 UTC, merged