SDKS-3458 Swift6 adoption + concurrency check
ForgeRock/ping-ios-sdk pull request #6
Opened 2024-10-24 06:15 UTC by jeyanthanperiyasamy

# JIRA Ticket

[SDKS-3458](https://pingidentity.atlassian.net/browse/SDKS-3458) DaVinci Swift 6.0 adoption (concurrency check)

# Description

Reduce the reliance on traditional classes as part of our commitment to improve compatibility with Swift 6 concurrency. This initial commit marks a step in that direction.

To achieve better thread safety, we should prioritize using actor, struct, and final class more frequently, while minimizing inheritance where possible. Embracing a concurrency-first pattern will help us leverage Swift’s capabilities more effectively.

We should continuously identify opportunities to decrease class usage, ensuring our code is both safe and efficient in a concurrent environment.

# Checklist:

- [ ] I ran all unit tests and they pass
- [ ] I added test case coverage for my changes

2024-10-31 17:42 UTC, spetrov approved these changes
LGTM!

2024-11-05 17:19 UTC, rodrigoareis commented on PingOrchestrate/PingOrchestrate/ThreadSafeHelper.swift
> +public struct SendableAny: @unchecked Sendable {
Add doc to the public methods

2024-11-05 17:21 UTC, rodrigoareis requested changes
Looks good to me. Just a minor comment to be addressed.

2024-11-06 17:15 UTC, witrisna approved these changes
Most of my comments are just question

2024-11-06 17:26 UTC, jeyanthanperiyasamy commented on PingDavinci/PingDavinci/collector/Form.swift
> +actor Form {
Form can be a struct ... we generally reduce using classes. For this scenario actor is not required.

2024-11-06 17:40 UTC, jeyanthanperiyasamy commented on PingDavinci/PingDavinci/collector/FieldCollector.swift
> +open class FieldCollector: Collector, @unchecked Sendable {
swift 6 compile will not this , so we need to tell compiler saying ignore to do a compability check   , 

Non-final class 'FieldCollector' cannot be conform to 'Sendable';

2024-11-06 17:44 UTC, jeyanthanperiyasamy commented on PingDavinci/PingDavinci/module/Oidc.swift
> +public actor OidcModule {
yes, customer will have to call like to add custom callback ..  

await CollectorFactory.shared.register(type: collector:)

2024-11-06 17:44 UTC, jeyanthanperiyasamy commented on PingDavinci/PingDavinci/collector/CollectorFactory.swift
> +public actor CollectorFactory {
yes, customer will have to call like to add custom callback ..  

await CollectorFactory.shared.register(type: collector:)

2024-11-06 18:10 UTC, jeyanthanperiyasamy commented on PingOidc/PingOidc/OidcUser.swift
> +public final class OidcUser: User, @unchecked Sendable {
To convert this to actor ,  we need to convert lot of other code to be sendable like AgentDelegate, OidcClient etc to be sendable . 

So i would slowly do that at some point

2024-11-06 18:30 UTC, jeyanthanperiyasamy commented on PingDavinci/PingDavinci/module/Oidc.swift
> +public actor OidcModule {
by default static property in classes are not thread safe. so compiler will throw error 

`Static property 'config' is not concurrency-safe because non-'Sendable' type 'Module<OidcClientConfig>' may have shared mutable state`

2024-11-06 18:42 UTC, jeyanthanperiyasamy commented on PingDavinci/PingDavinci/module/Oidc.swift
> +public actor OidcModule {
Let me think about this in another way

2025-03-26 19:00 UTC, vahancouver commented
outdated

2025-03-26 19:00 UTC, closed without merging